<a href="https://colab.research.google.com/github/tasnimislamraisa/Python_Learning/blob/cwh/CWH_V4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import numpy as np

In [28]:
array1=np.array([[3,2,5,7,0],[1,5,6,0,8]])
print(array1)
print(type(array1))

[[3 2 5 7 0]
 [1 5 6 0 8]]
<class 'numpy.ndarray'>


In [29]:
array1.shape
#(row,column)

(2, 5)

In [30]:
array1.dtype

dtype('int64')

In [31]:
#(row,column)
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [32]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [33]:
np.empty((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [34]:
#difference between np.zeros and np.empty

# np.zeros creates an array filled with zeros.
# np.empty creates an array without initializing its values.  It's faster, but the initial contents are unpredictable (garbage values).
# It's important to assign values to an array created with np.empty before using it.

# Example demonstrating the difference
import numpy as np

zeros_array = np.zeros((2, 3))
print("Zeros array:\n", zeros_array)

empty_array = np.empty((2, 3))
print("Empty array:\n", empty_array)

Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Empty array:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [40]:
print(array1)

[[3 2 5 7 0]
 [1 5 6 0 8]]


In [41]:
array1*array1

array([[ 9,  4, 25, 49,  0],
       [ 1, 25, 36,  0, 64]])

In [42]:
1/array1

<ipython-input-42-38a290605690>:1: RuntimeWarning: divide by zero encountered in divide
  1/array1


array([[0.33333333, 0.5       , 0.2       , 0.14285714,        inf],
       [1.        , 0.2       , 0.16666667,        inf, 0.125     ]])

# **Slicing**

In [ ]:
# prompt: slicing

# Slicing
print(array1[0, :])  # Accessing the first row
print(array1[:, 0])  # Accessing the first column
print(array1[0, 1:4])  # Accessing elements from index 1 to 3 in the first row
print(array1[0, ::-1]) #reversing the first row
print(array1[::-1,:]) #reversing the array