<a href="https://colab.research.google.com/github/tasnimislamraisa/Python_Learning/blob/main/Naive_bayes_employee.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Naive bayes on employee dataset**

In [171]:
import numpy as np
import pandas as pd
import sklearn

In [172]:
dataset=pd.read_csv('Employee - Employee.csv')

In [173]:
dataset.head()

Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0  Bachelors         2017  Bangalore            3   34    Male          No   
1  Bachelors         2013       Pune            1   28  Female          No   
2  Bachelors         2014  New Delhi            3   38  Female          No   
3    Masters         2016  Bangalore            3   27    Male          No   
4    Masters         2017       Pune            3   24    Male         Yes   

   ExperienceInCurrentDomain  LeaveOrNot  
0                          0           0  
1                          3           1  
2                          2           0  
3                          5           1  
4                          2           1

In [174]:
dataset.isnull().sum()

Education                    0
JoiningYear                  0
City                         0
PaymentTier                  0
Age                          0
Gender                       0
EverBenched                  0
ExperienceInCurrentDomain    0
LeaveOrNot                   0
dtype: int64

In [175]:
dataset.shape

(4653, 9)

from sklearn import preprocessing
col_cat = ['Gender']
lab_encoder = preprocessing.LabelEncoder()
for col in col_cat:
 dataset[col]=lab_encoder.fit_transform(dataset[col])
 col_cat = ['EverBenched']
lab_encoder = preprocessing.LabelEncoder()
for col in col_cat:
 dataset[col]=lab_encoder.fit_transform(dataset[col])

In [176]:
from sklearn.preprocessing import LabelEncoder

# Initialize the LabelEncoder
label_encoder = LabelEncoder()

# Apply Label Encoding to categorical columns
dataset['Gender'] = label_encoder.fit_transform(dataset['Gender'])
dataset['EverBenched'] = label_encoder.fit_transform(dataset['EverBenched'])
dataset['Education'] = label_encoder.fit_transform(dataset['Education'])
dataset['City'] = label_encoder.fit_transform(dataset['City'])

In [177]:
dataset.head()

Education  JoiningYear  City  PaymentTier  Age  Gender  EverBenched  \
0          0         2017     0            3   34       1            0   
1          0         2013     2            1   28       0            0   
2          0         2014     1            3   38       0            0   
3          1         2016     0            3   27       1            0   
4          1         2017     2            3   24       1            1   

   ExperienceInCurrentDomain  LeaveOrNot  
0                          0           0  
1                          3           1  
2                          2           0  
3                          5           1  
4                          2           1

In [178]:
# all rows all column expect the last column
X=dataset.iloc[:,0:8].values
# all rows ,last column
y=dataset.iloc[:,-1]

In [179]:
X[:5]

array([[   0, 2017,    0,    3,   34,    1,    0,    0],
       [   0, 2013,    2,    1,   28,    0,    0,    3],
       [   0, 2014,    1,    3,   38,    0,    0,    2],
       [   1, 2016,    0,    3,   27,    1,    0,    5],
       [   1, 2017,    2,    3,   24,    1,    1,    2]])

In [180]:

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [181]:
X.shape

(4653, 8)

In [182]:
X_train.shape

(3722, 8)

In [183]:
X_test.shape

(931, 8)

In [184]:
y.shape

(4653,)

In [185]:
y_train.shape

(3722,)

In [186]:
y_test.shape

(931,)

In [187]:

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)



In [188]:
X_train_scaled[:5]

array([[-0.50723758,  1.5665578 ,  0.24696159,  0.53507256,  0.12494244,
        -1.22392262,  2.94833993,  0.06046742],
       [-0.50723758, -1.64449028, -0.94062373,  0.53507256, -0.49620952,
        -1.22392262, -0.33917392,  1.33921584],
       [-0.50723758, -1.64449028,  1.43454691, -1.25266539, -0.49620952,
        -1.22392262, -0.33917392,  1.33921584],
       [-0.50723758, -0.03896624,  1.43454691,  0.53507256, -1.11736147,
        -1.22392262, -0.33917392, -0.5789068 ],
       [-0.50723758,  1.03138312, -0.94062373,  0.53507256, -1.11736147,
        -1.22392262, -0.33917392, -0.5789068 ]])

In [189]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [190]:
# Initialize and train the Gaussian Naive Bayes classifier
gnb = GaussianNB()
gnb.fit(X_train_scaled, y_train)

GaussianNB()

In [191]:

# Make predictions on the test set
y_pred = gnb.predict(X_test_scaled)


In [192]:
# Evaluate the model
from sklearn.metrics import accuracy_score,confusion_matrix,recall_score,f1_score,precision_score
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[491 128]
 [172 140]]


In [193]:
precision=precision_score(y_test,y_pred)
print("Precision:",precision)

Precision: 0.5223880597014925


In [194]:
recall=recall_score(y_test,y_pred)
print("Recall:",recall)

Recall: 0.44871794871794873


In [195]:
f1_score= f1_score(y_test,y_pred)
print("F1 Score:",f1_score)

F1 Score: 0.4827586206896552


In [196]:
accuracy_score=accuracy_score(y_test,y_pred)
print("Gaussian Naive Bayes model accuracy(in %):", accuracy_score*100)

Gaussian Naive Bayes model accuracy(in %): 67.7765843179377
